alert("click ok to play");
var randd1=  Math.floor(Math.random()*6) + 1;
alert(randd1);
var randd2=  Math.floor(Math.random()*6) + 1;
alert(randd2);
var collect=new Array();
collect[1]=new Image();
collect[1].src='images/.dice1.png';
collect[2]=new Image();
collect[2].src='images/.dice2.png';
collect[3]=new Image();
collect[3].src='images/.dice3.png';
collect[4]=new Image();
collect[4].src='images/.dice4.png';
collect[5]=new Image();
collect[5].src='images/.dice5.png';
collect[6]=new Image();
collect[6].src='images/.dice6.png';
document.querySelector(".img1").setAttribute("src",collect[randd1]);
document.querySelector(".img2").setAttribute("src",collect[randd2]);
